M48
; DRILL file {KiCad 7.0.7} date Fri May 24 10:33:24 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-24T10:33:24-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X1.8126Y2.5085
X1.8126Y2.3175
T2
X1.9319Y2.5203
X1.9319Y2.3057
T3
X-0.563Y2.913
X-0.563Y1.813
X1.437Y1.213
X1.487Y3.113
T0
M30
